---
# Source: opentelemetry-collector/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-opentelemetry-collector
  labels:
    helm.sh/chart: opentelemetry-collector-0.8.0
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: opentelemetry
    app.kubernetes.io/version: "0.37.1"
    app.kubernetes.io/managed-by: Helm
